services:
  - type: static
    name: bluzora-frontend
    env: static
    repo: https://github.com/Bluzora-glitch/Bluzora-Frontend
    branch: main
    buildCommand: "" # ไม่มีคำสั่ง build เพราะเรา build เองแล้ว
    staticPublishPath: web_output
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
